/* EngFit 영핏 - Week 4 Vocabulary Data */
const VOCAB = [
  ["enrich","질을 높이다"],["subject","과목"],["develop","계발하다, 개발하다"],
  ["communication","의사소통"],["skill","기술"],["continue","계속하다"],
  ["self-confidence","자신감"],["achieve","성과를 이루다, 성취하다"],["cause","하게 하다, 일으키다"],
  ["have a difficult time -ing","~하는 데 어려움을 갖다"],["material","자료, 재료"],
  ["day-to-day","매일 행해지는, 그날그날의"],["along with","~와 더불어"],["patience","인내심"],
  ["responsibility","책임감"],["carry over to","~로 옮겨지다"],["organize","정리하다, 조직하다"],
  ["slightly","약간"],["break","휴식"],["than usual","평소보다"],["boss","상사, 고용주"],
  ["unfortunately","불행하게도"],["mean","의미하다"],["no longer","더는 ~ 아니다"],
  ["cafeteria","구내식당"],["exactly","정확히"],["meal","식사"],["surprise","놀라게 하다"],
  ["pack up","~을 싸다, 꾸리다"],["in a long time","한동안"],["detective","탐정"],
  ["process","과정"],["clue","단서"],["solve","해결하다, 풀다"],["look for","~을 찾다"],
  ["draw","도출하다, 끌다"],["conclusion","결론"],["based on","~을 바탕으로"],
  ["observation","관찰"],["inference","추론"],["reason","근거, 이유"],["evidence","증거"],
  ["source","출처"],["cost","비용"],["limited","한정된, 제한된"],["amount","양"],
  ["search","검색, 탐색"],["obtain","얻다"],["article","기사"],["gain","얻다"],
  ["product","제품"],["take advantage of","~을 이용하다"],["include","포함하다"],
  ["decide","결정하다"],["for the most part","대부분의 경우에"],["throughout","~동안 죽"],
  ["wait for","~을 기다리다"],["subway","지하철"],["in this way","이런 식으로"],
  ["structure","구조화하다"],["daily routine","일과"],["spread out","~을 펼치다"],
  ["provide","제공하다"],["at least","적어도"],["public transportation","대중교통"],
  ["pay the price","대가를 치르다"],["physical","신체적인"],["natural","자연적인"],
  ["mountain range","산맥"],["ideal","이상적인"],["separation","구분"],["establish","확립하다"],
  ["recognize","인정하다"],["feature","특징"],["in reality","실제로"],["shift","변화하다, 바꾸다"],
  ["alter","바꾸다"],["frequently","빈번하게"],["determine","결정하다"],["location","위치, 장소"],
  ["household","가족, 가구"],["currently","지금, 현재"],["total","총계 ~가 되다"],
  ["perform","연기하다"],["indeed","사실"],["pond","연못"],["water lily","수련"],
  ["remove","제거하다"],["double","두 배로 되다"],["numerous","수가 많은, 무수한"],
  ["otherwise","그렇지 않으면"],["chore","잡일"],["argument","논쟁, 주장"],
  ["play a role","역할을 하다"],["take away","앗아가다, 없애다"],["attention","주의, 돌봄"],
  ["serious","심각한, 진지한"],["put ~ to use","~을 이용하다"],["trick","기술, 재주, 묘기 / 묘책"],
  ["avoid","피하다"],["capture","붙잡다, 획득하다"],["appreciate","고마워하다"],
  ["share","함께 쓰다"],["constant","거듭되는, 끊임없는 / 변치 않는 것"],
  ["faultfinding","책망, 흠잡기"],["sense of self-worth","자아 존중감"],["criticize","비판하다"],
  ["praise","칭찬하다"],["self-esteem","자존감"],["randomly","무작위로"],["average","평균의"],
  ["follow-up","후속의"],["coworker","동료"],["step back","뒤로 물러서다"],
  ["point of view","관점"],["jump to the conclusion","속단하다"],["fake","거짓된"],
  ["amaze","깜짝 놀라게 하다"],["remind A of B","A에게 B를 생각나게 하다"],["late","고인이 된"],
  ["stainless","스테인리스의"],["beg","조르다, 간청하다"],["blender","믹서기"],
  ["refrigerator","냉장고"],["escape","(기억 따위가) 사라지다"],["minor","사소한, 작은"],
  ["masterpiece","걸작"],["medium","수단, 매개"],["indigestion","소화불량"],
  ["symptom","증상"],["upper","위쪽의"],["digestion","소화"],
  ["millennia","millennium(천년)의 복수형"],["hardy","억센"],["overeating","과식"],
  ["fatty","지방이 많은, 기름진"],["nervousness","신경과민"],["from within","내부로부터"],
  ["fitting","적합한, 어울리는"],["define","정의하다"],["morality","도덕, 도덕성"],
  ["commonly","보편적으로, 흔히"],["be intended to","~하도록 의도되다"],
  ["lawlessness","무법"],["chaos","혼돈, 혼란"],["nursing bottle","젖병"],
  ["desperate","필사적인"],["set up","~을 설치하다"],["spectator","구경꾼"],
  ["appealing","매력적인"],["conduct","행하다"],["rate","평가하다"],["flavor","맛"],
  ["preference","선호"],["center","집중시키다"],["conclude","결론짓다"],
  ["influence","영향을 미치다 / 영향"],["container","용기, 그릇"],
  ["signal","신호를 보내다, 표시하다"],["nonverbal","비언어적인"],["cue","신호, 암시"],
  ["squarely","똑바로, 정면으로"],["posture","자세, 태도"],["attentiveness","관심을 쏟음"],
  ["disrespectful","무례한"],["startled","깜짝 놀란"],["apologize","사과하다"],
  ["slip away","슬그머니 가버리다"],["solution","용액"],["arrogant","오만한"],
  ["insane","미친"],["prevail","승리하다, 만연하다"],["profession","직업, 직종"],
  ["corporate","회사의"],["headquarters","본부, 본사"],["consciously","의식적으로"],
  ["stage","(일을) 연출하다, 벌이다"],["dramatic","극적인, 인상적인"],
  ["make a point","강조하다, 주장하다"],["fundamental","핵심적인, 필수적인"],
  ["executive","경영진"],["mew","야옹 하고 울다"],["adorable","사랑스러운"],
  ["kitten","새끼 고양이"],["ground","잘게 간"],["scrap","남은 음식"],
  ["prime rib","(최상등품) 소갈비"],["growl","으르렁거리다"],["savage","몹시 사나운"],
  ["tear apart","~을 갈가리 찢어 버리다"],["bother","일부러 애써 ~하다 / 괴롭히다"],
  ["negotiator","협상자"],["let off steam","울분을 발산하다"],["rationally","이성적으로"],
  ["give ~ a free hand","~가 제멋대로 행동하게 하다"],["interrupt","방해하다"],
  ["dissatisfaction","불만"],["variation","변형, 변형물"],["mechanism","구조, 기계 장치"],
  ["clasp","걸쇠"],["straight","곧은, 일직선의"],["circular","원형의"],["lid","뚜껑"],
  ["absent-minded","멍청한, 얼빠진"],["inhabitant","주민"],["native","원주민의, 토착민의"],
  ["Dutch","네덜란드의"],["sign up for","~에 등록하다"],["pension","연금"],
  ["contribution","개인 분담금"],["immediately","즉시, 곧"],["participation","참가"],
  ["plead","간청하다"],["pay off","성공하다"],["sharp","뚜렷한, 분명한"],
  ["appearance","외모"],["character","성질, 성격 / 등장인물"],["fearsome","무시무시한"],
  ["pointed","(끝이) 뾰족한"],["scary","무서운, 겁나게 하는"],
  ["companionship","동료애, 우정"],["cage","우리 속에 가두다"],["psychologist","심리학자"],
  ["leading","선도적인"],["expert","전문가"],["muscle","근육"],
  ["mirror","그대로 비추는 것"],["artificial","인공의, 인위적인"],["greet","인사하다"],
  ["operation","수술"],["patient","환자"],["statement","진술"],
  ["comforting","위로가 되는, 격려하는"],["react","반응하다"],
  ["content","내용 / 함유량 / 만족하는"],["eliminate","제거하다, 없애다"],
  ["disposable","일회용의"],["petroleum","석유"],["by-product","부산물"],
  ["dominate","지배하다"],["financially","재정적으로"],["sponsorship","후원, 지원"],
  ["expense","경비"],["committee","위원회"],["dinner dance","만찬을 곁들인 댄스파티"],
  ["up close","바로 가까이에"],["salmon","연어"],["eyesight","시력"],
  ["spot","찾아내다"],["swoop","급강하하다"],["scent","향기, 향내"],["awaken","깨우다"],
  ["in combination with","~와 결합하여"],["aroma","향기, 방향"],["impact","영향, 충격"],
  ["visibility","가시성, 시야"],["frequency","빈도"],["decisive","결정적인"],
  ["overlook","내려다 보다"],["gaze","응시하다"],["movie lot","영화 촬영소"],
  ["star","주연하다"],["refocus","다시 집중하다"],["forward","앞으로, 장래에"],
  ["remind","상기시키다"],["evolution","진화"],["parasite","기생충"],["habitat","서식지"],
  ["spawn","알을 낳다"],["vividly","분명히"],["witness","증인, 목격자"],
  ["tedious","지루한, 싫증나는"],["significant","중요한"],["relative","상대적인"],
  ["involve","연루시키다"],["status","지위"],["received pronunciation","표준 발음"],
  ["assume","추정하다"],["deviation","벗어남, 일탈"],["electronics","전자기기, 전자 장치"],
  ["charger","충전기"],["trickle","(가늘게) 흐르다"],["forefront","선두에 있는"],
  ["chronic","만성적인"],["candlelit","촛불을 밝힌"],["do the rest","나머지 역할을 다해 내다"],
  ["subdivide","세분화시키다"],["distribute","배포하다"],["objective","객관적인"],
  ["far-reaching","광범위한"],["spontaneously","자발적으로"],["intervention","개입"],
  ["mentality","심리"],["classical","고대의"],["skip","거르다, 건너뛰다"],
  ["nutritious","영양가 있는"],["recharge","재충전하다"],["efficient","능률적인"],
  ["genetic","유전의"],["graduation","졸업"],["community","동네, 마을"],["wallet","지갑"],
  ["affordable","(가격이) 알맞은"],["view A as B","A를 B로 여기다"],
  ["irresponsible","무책임한"],["unproductive","비생산적인"],["participant","참가자"],
  ["get down to business","본론에 착수하다"],["elementary","기본적인, 기초적인"],
  ["linguistic","언어의"],["reflect","반영하다"],["conventional","관습적인"],
  ["donation","기부"],["sponsor","후원하다"],["starving","굶주리는"],
  ["let go of","~을 놓아주다"],["describe","설명하다"],["associate","관련시키다"],
  ["quarrel","말다툼"],["intensively","격렬하게"],["take part in","~에 참여하다"],
  ["benefit","이익을 얻다 / 이점, 혜택"],["previously","전에"],["aging","노화"],
  ["perceive","인지하다"],["application","적용, 응용"],["scale","규모"],
  ["demonstrate","입증하다"],["on a regular basis","정기적으로"],
  ["confusing","혼란시키는"],["disturbing","불안감을 주는"],["at times","가끔"],
  ["handle","다스리다, 다루다"],["reassure","안심시키다"],["chase away","~을 쫓아내다"],
  ["pitch a tent","텐트를 치다"],["raw material","날 것, 원재료"],["mustache","콧수염"],
  ["possess","보유하다, 소유하다"],["parenting","육아"],["for the worse","나쁜 쪽으로"],
  ["fatigue","피로"],["ceaseless","끊임없는"],["diaper","기저귀"],
  ["cope with","~에 대처하다"],["rewarding","보람 있는"],["correlation","상관관계"],
  ["have to do with","~와 관계가 있다"],["in the first place","우선"],["loyalty","충성"],
  ["sense of belonging","소속감"],["take in","~을 섭취하다"],["occasional","가끔의"],
  ["caffeinated beverage","카페인이 함유된 음료"],["promote","(선전으로) 판촉하다"],
  ["treat","맛있는 음식, 대접"],["dramatically","급격하게, 극적으로"],
  ["electronics store","전자제품 판매점"],["go on","계속 (말 등을) 하다"],
  ["jealous","질투하는"],["eventually","결국"],["convinced","확신하는"],
  ["literature","문학 (작품)"],["reputation","평판, 명성"],["small-talk","잡담, 한담"],
  ["drunkard","술고래, 주정뱅이"],["routinely","일상적으로"],["contrast","대조하다"],
  ["strategy","전략"],["yell","소리치다"],["applaud","칭찬하다, 갈채를 보내다"],
  ["progress","발전"],["at the cost of","~를 희생하여"],["esteem","존중, 존경"],
  ["confidence","자신감"],["competent","유능한"],["constructive","건설적인"],
  ["obvious","분명한"],["theory","이론"],["a range of","일련의"],
  ["by far","(최상급 강조) 단연코"],["voyage","항해"],["volcanic","화산의"],
  ["roughly","대략"],["the Beagle","다윈이 탐험을 위해 타고 떠난 배의 이름"],
  ["reveal","드러내다, 보여주다"],["species","종(種)"],["beak","부리"],
  ["monk","수도승"],["purity","맑음, 청결"],["precious","귀중한, 소중한"],
  ["fragrant","향기로운"],["incense","향, 향료"],["carve","조각하다"],
  ["statue","조각상"],["consistent","한결같은"],["square","정사각형의"],
  ["essence","본질"],["metabolic","신진대사의"],["phenomenon","경이로운 사람, 현상"],
  ["contender","경쟁자"],["indulge in","~에 몰두하다, 빠지다"],["scorn","멸시, 경멸"],
  ["glitter","빛나다"],["perspective","시각, 관점"],["pastor","목사"],
  ["funeral service","장례식"],["sermon","설교"],["escort","호위, 호위대"],
  ["funeral coach","영구차, 장의차"],["cemetery","묘지"],["procession","행렬"],
  ["graveside service","묘지 예배"],["nickel","5센트"],["outfielder","(야구) 외야수"],
  ["profitable","수익성이 있는"],["handout","유인물, 수업 자료"],
  ["replace","대신하다, 대체하다"],["shorthand","속기"],["identify","확인하다"],
  ["low-spirited","우울한"],["weather","(역경 등을) 헤쳐 나가다"],
  ["addressee","수신인"],["batting average","타율"],["raw","날것의"],
  ["fluid","유동체, 유동체의"],["solid","고형의"],["fierce","거센, 맹렬한"],
  ["consult","(지도를) 보다"],["border","접하다"],["undergraduate","대학생의"],
  ["pull back","~에서 물러나다"],["handstand","물구나무서기"],["swallow","삼키다"],
  ["evaporate","증발하다"],["mineral","광물, 무기물"],["connect","연결하다"],
  ["generator","발전기"],["operate","작동시키다"],["out of shape","건강이 좋지 않은"],
  ["harvest","수확하다"],["hay","건초"],["block","막다, 방해하다"],
  ["practical joke","장난, 못된 장난"],["possibility","가능성"],["adopt","채택하다"],
  ["celebrate","축하하다"],["in time","이윽고"],["biological","생물학적인"],
  ["developmental","발달상의"],["rat","쥐"],["lick","핥다"],["curl","몸을 웅크리다"],
  ["limb","수족, 팔다리"],["sensory organ","감각 기관"],["incubator","보육기, 인큐베이터"],
  ["undisturbed","방해를 받지 않는"],["advantage","이점"],["physically","물리적으로"],
  ["dormitory","기숙사"],["stimulation","자극"],["abnormal","비정상적인"],
  ["self-destructive","자기 파괴적인"],["captivity","감금, 억류"],["distress","고통, 괴로움"],
  ["griot","그리오(서아프리카 구비 설화 이야기꾼)"],["spoken word","구어"],
  ["pass ~ on to ...","~을 …에게 전하다"],["by word of mouth","입에서 입으로"],
  ["initiate","시작하다"],["contract","계약"],["principle","원칙"],
  ["reap","거두다, 수확하다"],["mow","베어내다"],["strike a deal","거래를 체결하다"],
  ["defect","결점"],["ordinary","보통의, 일상적인"],["lens","렌즈"],
  ["readily","즉시, 쉽사리"],["striking","두드러지는, 눈에 띄는"],
  ["manager","(야구, 축구의) 감독"],["viewing rate","시청률"],["all the way","항상"],
  ["minority","소수"],["peak viewing hours","최고 시청 시간"],["proportion","비율"],
  ["framework","체제"],["secondary","부차적인"],["suppress","억제하다, 진압하다"],
  ["superficial","피상적인, 얄팍한"],["state of affairs","상황, 현상"],
  ["resolve","해결하다"],["appropriate","적절한"],["party","당사자"],
  ["instinct","본능"],["mosquito","모기"],["thorn","골칫거리, 가시"],
  ["existence","생활, 존재"],["picky","까다로운"],["reproduce","번식하다"],
  ["hatch","부화하다"],["nutrient","영양소, 영양분"],["nourishment","영양분"],
  ["simplify","단순화하다, 간단하게 하다"],["finite","한정된, 유한한"],
  ["language-specific","특정한 언어에 한정된"],["tonal language","성조 언어"],
  ["linguistics","언어학"],["phonetics","음성학"],["phonology","음운론"],
  ["incentive","장려금, 우대책"],["corporation","회사"],["back-up","후원, 지지"],
  ["stirring","마음을 뒤흔드는"],["applause","박수"],["outperform","더 나은 결과를 내다"],
  ["ultraviolet","자외선의"],["exposure","노출"],["abstract","추상적인"],
  ["prehistoric","선사 시대의"],["confront","직면하다"],["significantly","상당히"],
  ["gut","장"],["reside","(특정한 곳에) 살다"],["reluctantly","억지로"],
  ["hatred","증오심"]
];
